### PR TITLE
Refactor script

### PR DESCRIPTION
**Pull request by matthewtruty**
@Magic-Mayo I removed the else if in displayComments by moving the default query declaration above the if, then I changed how the HTML was written below. Instead of echoing out H2's, I made that HTML and added PHP tags for the function calls. Can you pull this branch down and move the function definitions to a new file and then reference the file they are located in at the top of index.php? Tag me in this pull request and I can review!

### CODE REVIEW

**Comment by matthewtruty** [comment]
We can continue the conversation in this PR

**Comment by Magic-Mayo** [comment]
Alright, I can do that.

**Comment by Magic-Mayo** [comment]
@matthewtruty I moved the functions to their own file.  I do have a question about what you did just so I'm understanding things a little better.  You said instead of echoing the h2 tags you made them HTML and then added PHP tags for the function calls.  What's the reasoning behind that?  Is it just to make things easier to look at and tell what it's doing or is there another reason for it?

**Comment by matthewtruty** [comment]
Yeah, in general, I would try to avoid echoing HTML and passing data to a view and keeping the HTML in that view. Laravel makes this easy with blade templates and an MVC approach: https://laravel.com/docs/8.x/blade#introduction

It can work either way and Sweetwater.com has a mix of both. New applications we write adhere to he Laravel style of passing data to a view and writing HTML in that view

**Comment by Magic-Mayo** [comment]
That makes sense!  Thanks

**Pull request merged**
